language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/pdgwien/mtg-emblems.git
  - secure: SR/yjmqEquLUjcwvTdq8Cy00QDbNXJKIuOoG7XCtqfs1YAfQtfXgmlEycDrGdkMJYPKPJFJRjl4IR9vvKyCrXGlIan3haQaxd3IvOFCJfNveyZZ7ib58ZLRzzLHGHPYp0Q75nbXsQ+BHhRO1Nq1qxc2uOcWxngEZAk7OlXdPQgk=
before_script:
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli bower
  - bower install
script: grunt build
after_success:
    # Any command that using GH_OAUTH_TOKEN must pipe the output to /dev/null to not expose your oauth token
    - git submodule add -b gh-pages https://$(GH_OAUTH_TOKEN)@$(GH_REF) site > /dev/null 2>&1
    - cd site
    - if git checkout gh-pages; then git checkout -b gh-pages; fi
    - git rm -r .
    - cp -R ../dist/* .
    - cp ../dist/.* .
    - git add -f .
    - git config user.email "pdgwien@gmail.com"
    - git config user.name "Patrick Grosslicht"
    - git commit -am "New build [ci skip]"
    # Any command that using GH_OAUTH_TOKEN must pipe the output to /dev/null to not expose your oauth token
    - git push --force https://$(GH_OAUTH_TOKEN)@$(GH_REF) HEAD:gh-pages > /dev/null 2>&1

