sudo: false
language: node_js
node_js:
- '6'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
env:
  global:
  - GH_REF: github.com/pdgwien/mtg-emblems.git
  - secure: Hp4RPVnrmjo+Hk8GkjtcBMJNR4+6zy76Dw0BdhhedylgTwuvnJEJYykX+pmrl/zMV4TG0Js9OgoVsKu3wbIMqLdZPoGV4tM34Jw/03epTBzcYKhOefxoZz++/EQ7P4djXm/pn1I84z/voJhBlNGpgvxGzi9Os12r2c5hLmST3mw=
before_script:
- gem update --system
- gem install compass --no-ri --no-rdoc
- npm install -g grunt-cli bower
- bower install
script: grunt
after_success:
- git submodule add -b gh-pages https://${GH_TOKEN}@${GH_REF} site > /dev/null 2>&1
- cd site
- if git checkout gh-pages; then git checkout -b gh-pages; fi
- git rm -r .
- cp -R ../dist/* .
- cp ../dist/.* .
- git add -A .
- git config user.email "pdgwien@gmail.com"
- git config user.name "Patrick Grosslicht"
- git commit -am "New build [ci skip]"
- git push --force https://${GH_TOKEN}@${GH_REF} HEAD:gh-pages > /dev/null 2>&1
